version: '3.8'

services:
  server:
    build:
      context: ./Server
    environment:
      - SERVER_ID=1  # Set the desired SERVER_ID as an example
    networks:
      - net1

  load_balancer:
    build:
      context: ./Load_Balancer
    ports:
      - "5000:5000"
    networks:
      - net1
    depends_on:
      - server

networks:
  net1:
