version: '3.8'

services:
  server:
    build:
      context: ./Server
    environment:
      - HOSTNAME=server  # Set the desired HOSTNAME as an example
    container_name: server
    networks:
      - net1

  load_balancer:
    build:
      context: ./Load_Balancer
    ports:
      - "5000:5000"
    networks:
      - net1
    depends_on:
      - server
    privileged: true
    container_name: load_balancer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  net1:
    driver: bridge